### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by Emasoft** [ffreemt/epub2txt#2]
I have some trouble with epub2txt:

``` bash
$
python3.9 -m pip install -U epub2txt
Defaulting to user installation because normal site-packages is not writeable
Collecting epub2txt
  Downloading epub2txt-0.1.1-py3-none-any.whl (7.2 kB)
Collecting httpx<0.17.0,>=0.16.1
  Downloading httpx-0.16.1-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 942.9 kB/s eta 0:00:00
Collecting ebooklib<0.18.0,>=0.17.1
  Using cached EbookLib-0.17.1.tar.gz (111 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm<5.0.0,>=4.56.0 in /private/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/lib/python3.9/site-packa
ges (from epub2txt) (4.64.0)
Collecting logzero<2.0.0,>=1.6.3
  Downloading logzero-1.7.0-py2.py3-none-any.whl (16 kB)
Collecting absl-py<0.12.0,>=0.11.0
  Downloading absl_py-0.11.0-py3-none-any.whl (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.8/127.8 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: six in /private/var/containers/Bundle/Application/E7256739-57A8-4912-9120-41AE0D008AD6/a-Shell-mini.app/Library/lib/python3.9/site-packages 
(from absl-py<0.12.0,>=0.11.0->epub2txt) (1.16.0)
Requirement already satisfied: lxml in /private/var/containers/Bundle/Application/E7256739-57A8-4912-9120-41AE0D008AD6/a-Shell-mini.app/Library/lib/python3.9/site-packages
 (from ebooklib<0.18.0,>=0.17.1->epub2txt) (4.7.1)
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting httpcore==0.12.*
  Downloading httpcore-0.12.3-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 1.5 MB/s eta 0:00:00
Collecting rfc3986[idna2008]<2,>=1.3
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: certifi in /private/var/containers/Bundle/Application/E7256739-57A8-4912-9120-41AE0D008AD6/a-Shell-mini.app/Library/lib/python3.9/site-packages (from httpx<0.17.0,>=0.16.1->epub2txt) (2021.10.8)
Collecting h11==0.*
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: idna in /private/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/lib/python3.9/site-packages (from rfc39
86[idna2008]<2,>=1.3->httpx<0.17.0,>=0.16.1->epub2txt) (3.3)
Building wheels for collected packages: ebooklib
  Building wheel for ebooklib (setup.py) ... done
  Created wheel for ebooklib: filename=EbookLib-0.17.1-py3-none-any.whl size=38184 sha256=3eab60333cf9034f671300269fecd1fb43fea1e02ac314f9aa1155253f5af4e1
  Stored in directory: /private/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/Caches/pip/wheels/b3/81/87/9b2b38976b783a8c2baffb72b320
d2af59f8da80e6cb6410fd
Successfully built ebooklib
Installing collected packages: rfc3986, logzero, sniffio, h11, ebooklib, absl-py, httpcore, httpx, epub2txt
Successfully installed absl-py-0.11.0 ebooklib-0.17.1 epub2txt-0.1.1 h11-0.13.0 httpcore-0.12.3 httpx-0.16.1 logzero-1.7.0 rfc3986-1.5.0 sniffio-1.2.0
[~shortcuts]$ epub2txt --help
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/bin/epub2txt", line 5, in <module>
    from epub2txt.__main__ import main
  File "/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/lib/python3.9/site-packages/epub2txt/__main__.py", line 11, in <module>
    from .browse_filename import browse_filename
  File "/var/mobile/Containers/Data/Application/5084B078-762C-4B3E-BAD8-69D1E6E9E6FF/Library/lib/python3.9/site-packages/epub2txt/browse_filename.py", line 9, in <module>
    import tkinter as Tkinter
  File "/private/var/containers/Bundle/Application/E7256739-57A8-4912-9120-41AE0D008AD6/a-Shell-mini.app/Library/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
$
```

My environment does not allow GUI, so tkinter is not configured. Can you remove the tkinter dependency, making it a pure CLI tool? Thanks.

**Comment by ffreemt** [comment]
Thanks for reporting.

Indeed, epub2txt will open a tkinter GUI in some cases. However, this does not prevent epub2xt from being installed in a non-GUI envitonment. I tried installing epub2txt 0.1.1 in several ubuntu vps without a problem.

Nevertheless, I made a prerelease 0.1.2a0 available that will run without tkinter. You can try it with `pip install epub2txt -U --pre`.

Please let me know if 0.1.2a0 solves your problem.

**Comment by Emasoft** [comment]
Works perfectly now! Thanks a lot! 😀
I tested with many ebooks and it works like a charm!

BTW, can you add the option to support wildcards to convert multiple files at once?
Like this:
```bash
$ epub2txt -f *.epub
```
Or this:
```
$ epub2txt -f "textbook - chapter *.epub"
```

**Comment by ffreemt** [comment]
That's a good idea thanks for the suggestion.

I'll need a bit more time to test and implement it though. I will try to incoporate it into 0.1.2.
